//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductPK { get; set; }
        public string productCode { get; set; }
        public string productName { get; set; }
        public Nullable<double> unitPrice { get; set; }
        public Nullable<double> discount { get; set; }
        public Nullable<int> buyQuantity { get; set; }
        public Nullable<int> getQuantity { get; set; }
        public Nullable<int> discountType { get; set; }
    }
}
